function [v_Coal,v_Oil,v_Gas,v_t,v_x_tot,v_emission,v_fossil,v_x_box0,v_x_box1,v_x_box2,v_x_box3]  = get_ss_v_nc_hybrid(Temp_SS,Phi_Emission,Discount_Factor_1,Discount_Factor_2,Discount_Factor_3,Discount_Factor_4,Discount_Factor_5,g_E,g_F, Y_AL, Y_Coal, Y_Oil, Y_Gas,... 
                                                                                  Y_Renewable, Y_Land, Y_Minerals, Y_Eco_Services, Y_K, V_Renewable, V_Land, V_Minerals, V_Eco_Services, V_K, V_AL, ...
                                                                                  d1_AL_1,d1_AL_2,d1_AL_3,d1_AL_4,d1_AL_5,  d1_K_1,d1_K_2,d1_K_3,d1_K_4,d1_K_5, d1_Coal_1, d1_Coal_2, d1_Coal_3,d1_Coal_4,d1_Coal_5, d1_Oil_1,d1_Oil_2,d1_Oil_3, d1_Oil_4, ...
                                                                                  d1_Oil_5, d1_Gas_1, d1_Gas_2,d1_Gas_3,d1_Gas_4,d1_Gas_5, d1_Renewable_1,d1_Renewable_2, ...
                                                                                  d1_Renewable_3, d1_Renewable_4,d1_Renewable_5, d1_Land_1,d1_Land_2,d1_Land_3,d1_Land_4,d1_Land_5, ...
                                                                                  d1_Minerals_1, d1_Minerals_2,d1_Minerals_3,d1_Minerals_4,d1_Minerals_5, d1_Eco_Services_1, d1_Eco_Services_2, ...
                                                                                  d1_Eco_Services_3,d1_Eco_Services_4,d1_Eco_Services_5,gamma_Coal, eps_F, Y_Fossil, ...
                                                                                  gamma_Oil, gamma_Gas, Beta, zetta_1, zetta_2, gamma_Fossil, V_Energy, eps_E, Y_Energy, e_A, ...
                                                                                  DELTA_X_0,DELTA_X_1,DELTA_X_2,DELTA_X_3,XI_E_0,XI_E_1,XI_E_2,XI_E_3,g_a)


                                                                                  
    % Define the equation to solve
    func = @(ss)[
        ss(1) - ss(7) * gamma_Coal * (Y_Coal)^(-1/eps_F) * (Y_Fossil)^(1/eps_F)*g_F^((eps_F-1)/eps_F);
        ss(2) - ss(7) * gamma_Oil * (Y_Oil)^(-1/eps_F) * (Y_Fossil)^(1/eps_F)*g_F^((eps_F-1)/eps_F);
        ss(3) - ss(7) * gamma_Gas * (Y_Gas)^(-1/eps_F) * (Y_Fossil)^(1/eps_F)*g_F^((eps_F-1)/eps_F);
        ss(4) - ( ...
               + Discount_Factor_1* (ss(1) * Temp_SS*d1_Coal_1 * Y_Coal) ...
               + Discount_Factor_2* (ss(1) * Temp_SS*d1_Coal_2 * Y_Coal) ...
               + Discount_Factor_3* (ss(1) * Temp_SS*d1_Coal_3 * Y_Coal) ...
               + Discount_Factor_4* (ss(1) * Temp_SS*d1_Coal_4 * Y_Coal)...
               + Discount_Factor_5* (ss(1) * Temp_SS*d1_Coal_5 * Y_Coal)...
               + Discount_Factor_1* (ss(2) * Temp_SS*d1_Oil_1 * Y_Oil)...
               + Discount_Factor_2* (ss(2) * Temp_SS*d1_Oil_2 * Y_Oil)...
               + Discount_Factor_3* (ss(2) * Temp_SS*d1_Oil_3 * Y_Oil)...
               + Discount_Factor_4* (ss(2) * Temp_SS*d1_Oil_4 * Y_Oil)...
               + Discount_Factor_5* (ss(2) * Temp_SS*d1_Oil_5 * Y_Oil)...
               + Discount_Factor_1* (ss(3) * Temp_SS*d1_Gas_1 * Y_Gas)...
               + Discount_Factor_2* (ss(3) * Temp_SS*d1_Gas_2 * Y_Gas)...
               + Discount_Factor_3* (ss(3) * Temp_SS*d1_Gas_3 * Y_Gas)...
               + Discount_Factor_4* (ss(3) * Temp_SS*d1_Gas_4 * Y_Gas)...
               + Discount_Factor_5* (ss(3) * Temp_SS*d1_Gas_5 * Y_Gas)...
               + Discount_Factor_1* (V_Renewable * Temp_SS*d1_Renewable_1 * Y_Renewable)...
               + Discount_Factor_2* (V_Renewable * Temp_SS*d1_Renewable_2 * Y_Renewable)...
               + Discount_Factor_3* (V_Renewable * Temp_SS*d1_Renewable_3 * Y_Renewable)...
               + Discount_Factor_4* (V_Renewable * Temp_SS*d1_Renewable_4 * Y_Renewable)...
               + Discount_Factor_5* (V_Renewable * Temp_SS*d1_Renewable_5 * Y_Renewable)...
               + Discount_Factor_1* (V_Land * Temp_SS*d1_Land_1 * Y_Land)...
               + Discount_Factor_2* (V_Land * Temp_SS*d1_Land_2 * Y_Land)...
               + Discount_Factor_3* (V_Land * Temp_SS*d1_Land_3 * Y_Land)...
               + Discount_Factor_4* (V_Land * Temp_SS*d1_Land_4 * Y_Land)...
               + Discount_Factor_5* (V_Land * Temp_SS*d1_Land_5 * Y_Land)...
               + Discount_Factor_1* (V_Minerals * Temp_SS*d1_Minerals_1 * Y_Minerals)...
               + Discount_Factor_2* (V_Minerals * Temp_SS*d1_Minerals_2 * Y_Minerals)...
               + Discount_Factor_3* (V_Minerals * Temp_SS*d1_Minerals_3 * Y_Minerals)...
               + Discount_Factor_4* (V_Minerals * Temp_SS*d1_Minerals_4 * Y_Minerals)...
               + Discount_Factor_5* (V_Minerals * Temp_SS*d1_Minerals_5 * Y_Minerals)...
               + Discount_Factor_1* (V_Eco_Services * Temp_SS*d1_Eco_Services_1 * Y_Eco_Services)...
               + Discount_Factor_2* (V_Eco_Services * Temp_SS*d1_Eco_Services_2 * Y_Eco_Services)...
               + Discount_Factor_3* (V_Eco_Services * Temp_SS*d1_Eco_Services_3 * Y_Eco_Services)...
               + Discount_Factor_4* (V_Eco_Services * Temp_SS*d1_Eco_Services_4 * Y_Eco_Services)...
               + Discount_Factor_5* (V_Eco_Services * Temp_SS*d1_Eco_Services_5 * Y_Eco_Services)...
               + Discount_Factor_1*(V_K * Temp_SS*d1_K_1 * Y_K) ...
               + Discount_Factor_2*(V_K * Temp_SS*d1_K_2 * Y_K) ...
               + Discount_Factor_3*(V_K * Temp_SS*d1_K_3 * Y_K) ...
               + Discount_Factor_4*(V_K * Temp_SS*d1_K_4 * Y_K) ...
               + Discount_Factor_5*(V_K * Temp_SS*d1_K_5 * Y_K)...
               + Discount_Factor_1*(V_AL * Temp_SS*d1_AL_1 * Y_AL) ...
               + Discount_Factor_2*(V_AL * Temp_SS*d1_AL_2 * Y_AL) ...
               + Discount_Factor_3*(V_AL * Temp_SS*d1_AL_3 * Y_AL) ...
               + Discount_Factor_4*(V_AL * Temp_SS*d1_AL_4 * Y_AL) ...
               + Discount_Factor_5*(V_AL * Temp_SS*d1_AL_5 * Y_AL)...
               ) /(Beta*(1-zetta_1) - (1+g_a)) ;       
        ss(5) - zetta_1*zetta_2*ss(4) ;
        ss(6) - (XI_E_0*ss(8) + XI_E_1*ss(9) + XI_E_2*ss(10) + XI_E_3*ss(11))* e_A;
        ss(7) - (V_Energy * gamma_Fossil * (Y_Fossil)^(-1/eps_E) * (Y_Energy)^(1/eps_E)*g_E^((eps_E-1)/eps_E) - ss(6)*Phi_Emission );    
        ss(8) - Beta*zetta_1*zetta_2*ss(4)/((1+g_a)-Beta*(1-DELTA_X_0));
        ss(9) - Beta*zetta_1*zetta_2*ss(4)/((1+g_a)-Beta*(1-DELTA_X_1));
        ss(10) - Beta*zetta_1*zetta_2*ss(4)/((1+g_a)-Beta*(1-DELTA_X_2));
        ss(11) - Beta*zetta_1*zetta_2*ss(4)/((1+g_a)-Beta*(1-DELTA_X_3));
];




    % Initial guess
    x0 = [1, 1, 1, 1, 1, 1, 1,1,1,1,1];

    % Options for fsolve
    options = optimset('Display', 'off', 'Algorithm', 'Levenberg-Marquardt', ...
        'MaxFunEvals', 10000, 'MaxIter', 10000, 'TolFun', 1e-16, 'TolX', 1e-8);

    % Solve the equation
    rez = fsolve(func, x0, options);

    % Output the solution
v_Coal = rez(1);
v_Oil = rez(2);
v_Gas = rez(3);
v_t = rez(4);
v_x_tot = rez(5);
v_emission = rez(6);
v_fossil = rez(7);
v_x_box0 = rez(8);
v_x_box1 = rez(9);
v_x_box2 = rez(10);
v_x_box3 = rez(11);

end

