function [V_T, V_X_TOT, V_Emission, V_Fossil] = get_ss_v_fossil_energy_hybrid_0(Temp_SS,Phi_Emission,V_Y_T,g_Y,V_AL,V_K,Y_T,eps_Y, Y_AL,Y_K, ...
                                                              d1_K_1, d1_K_2, d1_K_3, d1_K_4, d1_K_5, ...
                                                              d1_AL_1, d1_AL_2, d1_AL_3, d1_AL_4, d1_AL_5, ...
                                                              d1_Fossil_1,d1_Fossil_2 ,d1_Fossil_3,d1_Fossil_4,d1_Fossil_5, ...
                                                              Y_Fossil, gamma_Fossil, Beta, zetta_1, zetta_2, ...
                                                              DELTA_X_TOT)
                                                              

    % Define the equation to solve
    func = @(ss)[
        ss(1) - (...
               + Beta*(V_K * Temp_SS*d1_K_1 * Y_K) ...
               + Beta^2*(V_K * Temp_SS*d1_K_2 * Y_K) ...
               + Beta^3*(V_K * Temp_SS*d1_K_3 * Y_K) ...
               + Beta^4*(V_K * Temp_SS*d1_K_4 * Y_K) ...
               + Beta^5*(V_K * Temp_SS*d1_K_5 * Y_K)...
               + Beta*(V_AL * Temp_SS*d1_AL_1 * Y_AL) ...
               + Beta^2*(V_AL * Temp_SS*d1_AL_2 * Y_AL) ...
               + Beta^3*(V_AL * Temp_SS*d1_AL_3 * Y_AL) ...
               + Beta^4*(V_AL * Temp_SS*d1_AL_4 * Y_AL) ...
               + Beta^5*(V_AL * Temp_SS*d1_AL_5 * Y_AL)...
               + Beta* (ss(4) * Temp_SS*d1_Fossil_1 * Y_Fossil)...
               + Beta^2* (ss(4) * Temp_SS*d1_Fossil_2 * Y_Fossil)...
               + Beta^3* (ss(4) * Temp_SS*d1_Fossil_3 * Y_Fossil)...
               + Beta^4* (ss(4) * Temp_SS*d1_Fossil_4 * Y_Fossil)...
               + Beta^5* (ss(4) * Temp_SS*d1_Fossil_5 * Y_Fossil)...
                ) /(Beta*(1-zetta_1) - 1) ;
        ss(2) - Beta * zetta_1 * zetta_2 * ss(1) / (1 - Beta * (1 - DELTA_X_TOT));
        ss(3) - ss(2);
        ss(4) - (V_Y_T*gamma_Fossil*(Y_Fossil)^(-1/eps_Y)*(Y_T)^(1/eps_Y)*g_Y^((eps_Y-1)/eps_Y) - Phi_Emission*ss(3));    
     ];



    % Initial guess
    x0 = [1, 1, 1, 1];

    % Options for fsolve
    options = optimset('Display', 'off', 'Algorithm', 'Levenberg-Marquardt', ...
        'MaxFunEvals', 10000, 'MaxIter', 10000, 'TolFun', 1e-16, 'TolX', 1e-8);

    % Solve the equation
    rez = fsolve(func, x0, options);

    % Output the solution
    V_T = rez(1);
    V_X_TOT = rez(2);
    V_Emission = rez(3);
    V_Fossil = rez(4);
    
end

