clearvars; close all; clc;

script_dir = fileparts(mfilename('fullpath'));
root_dir = fileparts(script_dir);
tex_dir = fullfile(script_dir, 'results', 'tex_results');
utilities_dir = fullfile(script_dir, 'utilities');
if ~exist(tex_dir, 'dir')
    mkdir(tex_dir);
end
addpath(utilities_dir);

model_specs = struct( ...
    'name', {'NC_SCC_Hybrid', 'Fossil_SCC_Hybrid'}, ...
    'dir', {fullfile(root_dir, 'NC_Model'), fullfile(root_dir, 'Fossil_Model')});

moments_param_name = 'EPS_Y';
moments_param_values = [0.85, 0.99, 1.93];
moments_display_variables = {'v_emission', 'v_Energy', 'v_Fossil', 'v_Oil', 'v_Gas', 'v_Coal', 'v_Renewable', 'v_Minerals', 'v_Eco_Services', 'v_Land'};
moments_real_names = {'Shadow Cost of Emission', 'Shadow Cost of Energy', 'Shadow Cost of Fossil', 'Shadow Cost of Oil', 'Shadow Cost of Gas', 'Shadow Cost of Coal', 'Shadow Cost of Renewable Energy', 'Shadow Cost of Minerals', 'Shadow Cost of Forest ES', 'Shadow Cost of Land'};
moments_latex_names = { ...
    '$\mathbb{E}\!\left(V^{\text{E}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{E}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{FE}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{O}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{G}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{C}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{RE}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{M}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{FO}}\right)$', ...
    '$\mathbb{E}\!\left(\Psi^{\text{L}}\right)$'};

table_specs = struct( ...
    'name', {'paper_table4', 'paper_table5', 'paper_table30', 'paper_table31', 'paper_table33', 'paper_table34'}, ...
    'habits', {0, 0, 1, 1, 1, 0}, ...
    'shock_index', {1, 3, 1, 3, 2, 2}, ...
    'shock_variance', {0.01^2, 0.01, 0.01^2, 0.01, 0.01, 0.01}, ...
    'caption', { ...
        'Uncertainty cost of TFP shock for different $\theta$ values -- percentage change with respect to deterministic case', ...
        'Uncertainty cost of Temperature shock for different $\theta$ values -- percentage change with respect to deterministic case', ...
        'Uncertainty cost of TFP shock for different $\theta$ values -- percentage change with respect to deterministic case (with habits)', ...
        'Uncertainty cost of Temperature shock for different $\theta$ values -- percentage change with respect to deterministic case (with habits)', ...
        'Uncertainty cost of transient temperature parameter shock for different $\theta$ values -- percentage change with respect to deterministic case (with habits)', ...
        'Uncertainty cost of transient temperature parameter shock for different $\theta$ values -- percentage change with respect to deterministic case'});

for ispec = 1:length(table_specs)
    moments_spec = table_specs(ispec);
    run(fullfile(utilities_dir, 'ss_run_moments_table.m'));
    ss_write_moments_table(tex_dir, moments_spec.name, moments_spec.caption, moments_param_values, moments_table_mean, moments_table_std, moments_real_names, moments_latex_names);
end
